github.com:
    users:
        InvAwet:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: InvAwet
